// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOtWl4thluFzrZ9SMKa1onDJ31npXuwyI',
    appId: '1:604639735437:web:0f279f66aa14a7e2c43cc4',
    messagingSenderId: '604639735437',
    projectId: 'presupuestapp-fe73d',
    authDomain: 'presupuestapp-fe73d.firebaseapp.com',
    storageBucket: 'presupuestapp-fe73d.appspot.com',
    measurementId: 'G-R0ZH4B14RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTuXV_i5FfxGt9AG_itYuoD5wE0j5rCw',
    appId: '1:604639735437:android:9e679844438aad34c43cc4',
    messagingSenderId: '604639735437',
    projectId: 'presupuestapp-fe73d',
    storageBucket: 'presupuestapp-fe73d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQP1wd93TygHT48D9ififmnswhCzIpMaA',
    appId: '1:604639735437:ios:1e98e557c6a9ebd5c43cc4',
    messagingSenderId: '604639735437',
    projectId: 'presupuestapp-fe73d',
    storageBucket: 'presupuestapp-fe73d.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQP1wd93TygHT48D9ififmnswhCzIpMaA',
    appId: '1:604639735437:ios:1e98e557c6a9ebd5c43cc4',
    messagingSenderId: '604639735437',
    projectId: 'presupuestapp-fe73d',
    storageBucket: 'presupuestapp-fe73d.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOtWl4thluFzrZ9SMKa1onDJ31npXuwyI',
    appId: '1:604639735437:web:d58dd84a23fb5f76c43cc4',
    messagingSenderId: '604639735437',
    projectId: 'presupuestapp-fe73d',
    authDomain: 'presupuestapp-fe73d.firebaseapp.com',
    storageBucket: 'presupuestapp-fe73d.appspot.com',
    measurementId: 'G-QNLTV9FEZH',
  );
}
